# Generated by Django 4.2.7 on 2026-01-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0003_add_generation_config_and_stream_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasegenerationtask',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('generating', '生成中'), ('reviewing', '评审中'), ('revising', '改进中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
