# Generated by Django 4.2.7 on 2026-07-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0008_kb_reference_enhancement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='max_tokens',
            field=models.IntegerField(default=8192, verbose_name='最大Token数'),
        ),
        migrations.AlterField(
            model_name='generationconfig',
            name='review_timeout',
            field=models.IntegerField(default=3600, help_text='AI评审和改进的最大等待时间（总时长），0 表示不限制', verbose_name='评审和改进超时时间（秒）'),
        ),
    ]
