# Generated by Django 4.2.7 on 2026-07-08 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0014_testcasegenerationtask_refinement_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skill名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('icon', models.CharField(blank=True, default='🎯', max_length=10, verbose_name='图标(emoji)')),
                ('category', models.CharField(choices=[('general', '通用'), ('api', 'API测试'), ('ui', 'UI测试'), ('performance', '性能测试'), ('security', '安全测试'), ('mobile', '移动端测试'), ('integration', '集成测试'), ('custom', '自定义')], default='general', max_length=20, verbose_name='分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('generation_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='requirement_analysis.generationconfig', verbose_name='生成行为配置')),
                ('reviewer_model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_as_reviewer', to='requirement_analysis.aimodelconfig', verbose_name='评审模型配置')),
                ('reviewer_prompt_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_as_reviewer', to='requirement_analysis.promptconfig', verbose_name='评审提示词配置')),
                ('writer_model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_as_writer', to='requirement_analysis.aimodelconfig', verbose_name='编写模型配置')),
                ('writer_prompt_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_as_writer', to='requirement_analysis.promptconfig', verbose_name='编写提示词配置')),
            ],
            options={
                'verbose_name': '测试用例Skill',
                'verbose_name_plural': '测试用例Skill',
                'db_table': 'testcase_skill',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
