# Generated by Django 4.2.7 on 2026-07-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0017_kb_hub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcaseskill',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Skill技能包', 'verbose_name_plural': 'Skill技能包'},
        ),
        migrations.RenameIndex(
            model_name='nativekbchunk',
            new_name='kb_hub_nati_documen_2d351a_idx',
            old_name='kb_hub_chunk_doc_idx',
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('browser_use_text', 'Browser Use - 文本模式'), ('browser_use_vision', 'Browser Use - 视觉模式'), ('vision', '视觉理解模型')], max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='knowledgehubconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nativekb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nativekbchunk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nativekbdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
