# Generated by Django 4.2.7 on 2026-07-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0019_skill_template_and_task_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseskill',
            name='author',
            field=models.CharField(blank=True, default='', help_text='技能包作者，用于导入导出时的归属标记', max_length=100, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='testcaseskill',
            name='input_spec',
            field=models.JSONField(blank=True, default=dict, help_text='期望的输入类型与说明，如 {"type":"prd|swagger|image|free","description":"..."}', verbose_name='输入规范'),
        ),
        migrations.AddField(
            model_name='testcaseskill',
            name='output_spec',
            field=models.JSONField(blank=True, default=dict, help_text='输出格式与列定义，如 {"format":"markdown|json|excel|xmind","columns":[...],"description":"..."}', verbose_name='输出规范'),
        ),
        migrations.AddField(
            model_name='testcaseskill',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='标签列表，如 ["api","security"]', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='testcaseskill',
            name='tools',
            field=models.JSONField(blank=True, default=list, help_text='该技能可使用的工具/能力标识列表，如 ["run_api_test","run_ui_test_suite"]', verbose_name='关联工具'),
        ),
    ]
