# Generated by Django 4.2.7 on 2026-07-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0022_seed_perf_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseskill',
            name='skill_type',
            field=models.CharField(choices=[('requirements_analysis', '需求分析'), ('requirement_reviewer', '需求评审'), ('testcase_reviewer', '用例评审'), ('testcase_generator', '用例生成'), ('digital_human', '数字人'), ('custom', '自定义')], default='testcase_generator', max_length=30, verbose_name='技能类型'),
        ),
    ]
