# Generated by Django 4.2.7 on 2026-07-21 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0023_alter_testcaseskill_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseskill',
            name='package_files',
            field=models.JSONField(blank=True, default=dict, help_text='结构化文件内容：{"assets": [...], "input": [...], "references": [...], "scripts": [...]}', verbose_name='包内文件'),
        ),
        migrations.AddField(
            model_name='testcaseskill',
            name='readme',
            field=models.TextField(blank=True, default='', help_text='技能包说明文档（Markdown）', verbose_name='README.md'),
        ),
        migrations.AddField(
            model_name='testcaseskill',
            name='trigger_keywords',
            field=models.JSONField(blank=True, default=list, help_text='触发该 Skill 的关键词列表，如 ["生成测试用例", "PRD转测试用例"]', verbose_name='触发关键词'),
        ),
        migrations.CreateModel(
            name='SkillArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('asset', 'assets'), ('input', 'input'), ('reference', 'references'), ('script', 'scripts'), ('other', 'other')], default='other', max_length=20, verbose_name='文件类型')),
                ('path', models.CharField(max_length=500, verbose_name='包内路径')),
                ('file', models.FileField(blank=True, null=True, upload_to='skill_artifacts/%Y/%m/', verbose_name='文件')),
                ('text_content', models.TextField(blank=True, default='', verbose_name='文本内容')),
                ('is_binary', models.BooleanField(default=False, verbose_name='是否二进制')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='requirement_analysis.testcaseskill', verbose_name='所属 Skill')),
            ],
            options={
                'verbose_name': 'Skill 文件',
                'verbose_name_plural': 'Skill 文件',
                'db_table': 'skill_artifact',
                'ordering': ['artifact_type', 'path'],
                'unique_together': {('skill', 'path')},
            },
        ),
    ]
