# Generated by Django 4.2.7 on 2026-07-23 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_prj_module_idx_project_map_project_772106_idx'),
        ('requirement_analysis', '0024_testcaseskill_package_files_testcaseskill_readme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nativekb',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='全局共享'),
        ),
        migrations.CreateModel(
            name='ProjectKbBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bindings', to='requirement_analysis.nativekb', verbose_name='知识库')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_bindings', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '知识库项目绑定',
                'verbose_name_plural': '知识库项目绑定',
                'db_table': 'kb_hub_project_kb_binding',
                'unique_together': {('project', 'kb')},
            },
        ),
    ]
