# Generated by Django 4.2.7 on 2026-07-23 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0025_add_kb_global_and_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='KbSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='数据源名称')),
                ('external_type', models.CharField(choices=[('feishu', '飞书知识库'), ('confluence', 'Confluence'), ('notion', 'Notion')], default='feishu', max_length=32, verbose_name='外部类型')),
                ('app_id', models.CharField(blank=True, default='', max_length=200, verbose_name='App ID')),
                ('app_secret', models.CharField(blank=True, default='', max_length=400, verbose_name='App Secret')),
                ('tenant_key', models.CharField(blank=True, default='', max_length=200, verbose_name='Tenant Key')),
                ('base_url', models.URLField(blank=True, default='https://open.feishu.cn', verbose_name='API 基础地址')),
                ('sync_status', models.CharField(choices=[('pending', '未同步'), ('syncing', '同步中'), ('success', '同步成功'), ('failed', '同步失败')], default='pending', max_length=16, verbose_name='同步状态')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('last_sync_error', models.TextField(blank=True, default='', verbose_name='同步错误')),
                ('doc_count', models.PositiveIntegerField(default=0, verbose_name='文档数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('target_kb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='requirement_analysis.nativekb', verbose_name='目标知识库')),
            ],
            options={
                'verbose_name': '外部知识源',
                'verbose_name_plural': '外部知识源',
                'db_table': 'kb_hub_kb_source',
                'ordering': ['-updated_at'],
            },
        ),
    ]
