# Generated by Django 4.2.7 on 2026-07-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_prj_module_idx_project_map_project_772106_idx'),
        ('assistant', '0007_hermesmessage_images_hermesimage'),
        ('requirement_analysis', '0026_add_kb_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDifyKbBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=128, verbose_name='Dify 数据集 ID')),
                ('dataset_name', models.CharField(blank=True, default='', max_length=255, verbose_name='数据集名称')),
                ('document_count', models.PositiveIntegerField(default=0, verbose_name='文档数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('dify_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_kb_bindings', to='assistant.difyconfig', verbose_name='Dify 配置')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dify_kb_bindings', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目-Dify知识库绑定',
                'verbose_name_plural': '项目-Dify知识库绑定',
                'db_table': 'kb_hub_project_dify_kb_binding',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'dataset_id')},
            },
        ),
    ]
