# Generated by Django 4.2.7 on 2026-07-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0027_projectdifykbbinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbsource',
            name='feishu_mode',
            field=models.CharField(choices=[('wiki', '知识库'), ('drive', '云盘（云文档）')], default='wiki', max_length=16, verbose_name='飞书接入方式'),
        ),
        migrations.AddField(
            model_name='kbsource',
            name='feishu_root_folder_token',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='云盘根目录 Token'),
        ),
        migrations.AlterField(
            model_name='kbsource',
            name='external_type',
            field=models.CharField(choices=[('feishu', '飞书'), ('confluence', 'Confluence'), ('notion', 'Notion')], default='feishu', max_length=32, verbose_name='外部类型'),
        ),
    ]
