# Generated by Django 4.2.7 on 2026-07-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_prj_module_idx_project_map_project_772106_idx'),
        ('requirement_analysis', '0028_kbsource_feishu_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProjectBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bindings', to='requirement_analysis.nativekbdocument', verbose_name='文档')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_bindings', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '文档项目绑定',
                'verbose_name_plural': '文档项目绑定',
                'db_table': 'kb_hub_document_project_binding',
                'indexes': [models.Index(fields=['project'], name='kb_hub_docu_project_1b6269_idx'), models.Index(fields=['document'], name='kb_hub_docu_documen_9fb26e_idx')],
                'unique_together': {('project', 'document')},
            },
        ),
    ]
