# Generated by Django 4.2.7 on 2026-07-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0029_documentprojectbinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelconfig',
            name='api_key_env',
            field=models.CharField(blank=True, help_text='若填写，运行时优先从同名环境变量读取密钥，避免明文入库', max_length=100, null=True, verbose_name='API Key 环境变量名'),
        ),
    ]
