# Generated by Django 4.2.7 on 2026-08-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpcalllog',
            name='args_brief',
            field=models.TextField(blank=True, db_comment='脱敏截断后的参数JSON(供审计回溯)', default='', verbose_name='参数详情'),
        ),
        migrations.AddField(
            model_name='mcpcalllog',
            name='client_name',
            field=models.CharField(blank=True, db_comment='发起调用的客户端标识(User-Agent)', default='', max_length=100, verbose_name='客户端'),
        ),
        migrations.AddField(
            model_name='mcppendingconfirm',
            name='awaiting_human',
            field=models.BooleanField(db_comment='人工审批模式下 confirm 已转待批', default=False, verbose_name='等待人工审批'),
        ),
    ]
