# Generated by Django 4.2.7 on 2026-07-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectmapping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectmapping',
            new_name='project_map_project_772106_idx',
            old_name='prj_module_idx',
        ),
    ]
