# Generated by Django 4.2.7 on 2026-07-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('api_testing', '接口测试'), ('ui_automation', 'UI自动化'), ('app_automation', 'APP自动化'), ('performance_testing', '性能测试')], max_length=30, verbose_name='所属模块')),
                ('module_task_id', models.BigIntegerField(verbose_name='模块任务ID')),
                ('q_schedule_id', models.BigIntegerField(blank=True, null=True, verbose_name='Django-Q2 Schedule ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否已启用调度')),
                ('last_sync_at', models.DateTimeField(auto_now=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '调度绑定',
                'verbose_name_plural': '调度绑定',
                'db_table': 'scheduler_schedule_binding',
                'unique_together': {('module', 'module_task_id')},
            },
        ),
    ]
