# Generated by Django 4.2.7 on 2026-07-28 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('executions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRunCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='步骤序号')),
                ('action', models.TextField(verbose_name='操作')),
                ('expected', models.TextField(verbose_name='预期结果')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('status', models.CharField(choices=[('untested', '未测试'), ('passed', '通过'), ('failed', '失败'), ('blocked', '阻塞'), ('retest', '重测')], default='untested', max_length=20, verbose_name='执行状态')),
                ('comments', models.TextField(blank=True, verbose_name='备注')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('run_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_records', to='executions.testruncase', verbose_name='执行用例')),
            ],
            options={
                'verbose_name': '执行用例步骤',
                'verbose_name_plural': '执行用例步骤',
                'db_table': 'test_run_case_steps',
                'ordering': ['step_number'],
                'unique_together': {('run_case', 'step_number')},
            },
        ),
    ]
