# Generated by Django 4.2.7 on 2026-07-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0029_documentprojectbinding'),
        ('testcases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exec_testcases', to='requirement_analysis.businessrequirement', verbose_name='关联需求'),
        ),
    ]
