# Generated by Django 4.2.7 on 2026-07-28 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0030_aimodelconfig_api_key_env'),
        ('testcases', '0003_testcase_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_steps', models.JSONField(default=list, verbose_name='输入步骤')),
                ('prompt', models.TextField(blank=True, verbose_name='提示词')),
                ('suggestions', models.JSONField(default=list, verbose_name='建议补充步骤')),
                ('risks', models.JSONField(default=list, verbose_name='风险点')),
                ('summary', models.TextField(blank=True, verbose_name='总结')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Token 用量')),
                ('elapsed_ms', models.IntegerField(default=0, verbose_name='耗时(毫秒)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_analyses', to='requirement_analysis.aimodelconfig', verbose_name='AI 模型')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_analyses', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_analyses', to='requirement_analysis.businessrequirement', verbose_name='关联需求')),
                ('testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='testcases.testcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': 'AI 用例分析',
                'verbose_name_plural': 'AI 用例分析',
                'db_table': 'case_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
