# Generated by Django 4.2.7 on 2026-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(choices=[('UI', 'UI 自动化'), ('API', '接口测试'), ('APP', 'APP 自动化'), ('PERF', '性能测试'), ('UNKNOWN', '未知')], default='UNKNOWN', max_length=20, verbose_name='执行链路')),
                ('execution_id', models.CharField(db_index=True, max_length=64, verbose_name='执行ID')),
                ('step_key', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='步骤标识')),
                ('attempt_no', models.PositiveIntegerField(default=1, verbose_name='尝试序号')),
                ('trigger_category', models.CharField(choices=[('NETWORK_TIMEOUT', '网络超时'), ('CONNECTION_ERROR', '连接失败'), ('ASSERTION_ERROR', '断言失败'), ('LOCATOR_NOT_FOUND', '定位器未找到'), ('ELEMENT_NOT_FOUND', '元素未找到'), ('ELEMENT_NOT_INTERACTABLE', '元素不可交互'), ('AUTH_ERROR', '鉴权失败'), ('HTTP_4XX', '客户端错误(4xx)'), ('HTTP_5XX', '服务端错误(5xx)'), ('DEVICE_OFFLINE', '设备离线'), ('APP_CRASH', '应用崩溃'), ('TIMEOUT', '执行超时'), ('UNKNOWN', '未知错误')], default='UNKNOWN', max_length=30, verbose_name='触发分类')),
                ('success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '重试尝试',
                'verbose_name_plural': '重试尝试',
                'db_table': 'execution_retry_attempt',
                'ordering': ['execution_id', 'step_key', 'attempt_no'],
                'indexes': [models.Index(fields=['chain', 'execution_id'], name='execution_r_chain_900301_idx'), models.Index(fields=['chain', 'execution_id', 'step_key'], name='execution_r_chain_ba3759_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(choices=[('UI', 'UI 自动化'), ('API', '接口测试'), ('APP', 'APP 自动化'), ('PERF', '性能测试'), ('UNKNOWN', '未知')], default='UNKNOWN', max_length=20, verbose_name='执行链路')),
                ('execution_id', models.CharField(db_index=True, help_text='套件执行 / 运行 ID，兼容 UUID 与自增主键', max_length=64, verbose_name='执行ID')),
                ('step_key', models.CharField(blank=True, db_index=True, default='', help_text='执行内部的步骤标识（如步骤序号 / 用例ID），可为空表示整次执行', max_length=128, verbose_name='步骤标识')),
                ('evidence_type', models.CharField(choices=[('SCREENSHOT', '截图'), ('REQUEST_RESPONSE', '请求响应'), ('LOG', '日志'), ('HAR', 'HAR'), ('VIDEO', '视频'), ('CONSOLE', '控制台'), ('TRACE', '调用链'), ('OTHER', '其他')], max_length=40, verbose_name='证据类型')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='灵活结构：路径、状态码、URL、头部摘要、正文片段、时长等', verbose_name='证据内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
            ],
            options={
                'verbose_name': '执行证据',
                'verbose_name_plural': '执行证据',
                'db_table': 'execution_evidence',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['chain', 'execution_id'], name='execution_e_chain_c40b56_idx'), models.Index(fields=['chain', 'execution_id', 'step_key'], name='execution_e_chain_c64ee9_idx')],
            },
        ),
    ]
