# Generated by Django 4.2.7 on 2026-07-27 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requirement_analysis', '0029_documentprojectbinding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('executions', '0002_initial'),
        ('versions', '0001_initial'),
        ('projects', '0004_rename_prj_module_idx_project_map_project_772106_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.CharField(choices=[('GO', '可发布'), ('CONDITIONAL_GO', '有条件发布'), ('NO_GO', '不可发布')], max_length=20, verbose_name='发布结论')),
                ('metrics', models.JSONField(default=dict, verbose_name='评估指标')),
                ('reasons', models.JSONField(default=list, verbose_name='结论原因')),
                ('thresholds', models.JSONField(default=dict, verbose_name='使用阈值')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_releases', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_conclusions', to='projects.project', verbose_name='所属项目')),
                ('test_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_conclusions', to='executions.testrun', verbose_name='关联执行')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_conclusions', to='versions.version', verbose_name='关联版本')),
            ],
            options={
                'verbose_name': '发布结论',
                'verbose_name_plural': '发布结论',
                'db_table': 'release_conclusions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='缺陷标题')),
                ('description', models.TextField(blank=True, verbose_name='缺陷描述')),
                ('severity', models.CharField(choices=[('S1', '致命'), ('S2', '严重'), ('S3', '一般'), ('S4', '轻微')], default='S3', max_length=4, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('resolved', '已修复'), ('closed', '已关闭'), ('reopened', '重新打开')], default='open', max_length=20, verbose_name='状态')),
                ('steps_to_reproduce', models.TextField(blank=True, verbose_name='复现步骤')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to=settings.AUTH_USER_MODEL, verbose_name='指派人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='projects.project', verbose_name='所属项目')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='requirement_analysis.businessrequirement', verbose_name='关联需求')),
                ('test_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='executions.testrun', verbose_name='关联执行')),
                ('test_run_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects_obj', to='executions.testruncase', verbose_name='关联执行用例')),
            ],
            options={
                'verbose_name': '缺陷',
                'verbose_name_plural': '缺陷',
                'db_table': 'defects',
                'ordering': ['-created_at'],
            },
        ),
    ]
