# Generated by Django 4.2.7 on 2026-07-28 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='environment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='环境信息'),
        ),
        migrations.AddField(
            model_name='defect',
            name='source',
            field=models.CharField(blank=True, default='manual', help_text='manual=手动创建 / execution=用例执行 / performance=性能测试 / hermes=数字人 / ai=AI分析', max_length=50, verbose_name='缺陷来源'),
        ),
        migrations.CreateModel(
            name='DefectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('screenshot', '截图'), ('log', '日志'), ('video', '录像'), ('other', '其他')], default='screenshot', max_length=20, verbose_name='附件类型')),
                ('file', models.FileField(upload_to='defects/%Y/%m/', verbose_name='文件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME 类型')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='说明')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='defects.defect', verbose_name='所属缺陷')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_defect_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '缺陷附件',
                'verbose_name_plural': '缺陷附件',
                'db_table': 'defect_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
