# Generated by Django 4.2.7 on 2026-01-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='task_type',
            field=models.CharField(blank=True, help_text='发送通知时的任务类型', max_length=20, null=True, verbose_name='任务类型快照'),
        ),
    ]
