# Generated by Django 4.2.7 on 2026-02-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0004_apirequest_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationlog',
            name='task_type',
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api_testing.apicollection', verbose_name='所属集合'),
        ),
    ]
