# Generated by Django 4.2.7 on 2026-07-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0005_remove_notificationlog_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='extractors',
            field=models.JSONField(blank=True, default=list, verbose_name='变量提取器'),
        ),
    ]
