# Generated by Django 4.2.7 on 2026-07-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_prj_module_idx_project_map_project_772106_idx'),
        ('api_testing', '0006_add_extractors_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='api_scripts', to='projects.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=16, verbose_name='状态'),
        ),
    ]
