# Generated by Django 4.2.7 on 2026-07-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0007_apirequest_projects_apirequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='api_scripts', to='api_testing.apiproject', verbose_name='关联项目'),
        ),
    ]
