# Generated by Django 4.2.7 on 2026-07-24 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_prj_module_idx_project_map_project_772106_idx'),
        ('api_testing', '0008_alter_apirequest_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_subprojects', to='projects.project', verbose_name='关联主项目'),
        ),
    ]
