# Generated by Django 4.2.7 on 2026-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0009_apiproject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='evidence_summary',
            field=models.TextField(blank=True, default='', verbose_name='证据摘要'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='failure_category',
            field=models.CharField(blank=True, choices=[('NETWORK_TIMEOUT', '网络超时'), ('CONNECTION_ERROR', '连接失败'), ('ASSERTION_ERROR', '断言失败'), ('LOCATOR_NOT_FOUND', '定位器未找到'), ('ELEMENT_NOT_FOUND', '元素未找到'), ('ELEMENT_NOT_INTERACTABLE', '元素不可交互'), ('AUTH_ERROR', '鉴权失败'), ('HTTP_4XX', '客户端错误(4xx)'), ('HTTP_5XX', '服务端错误(5xx)'), ('DEVICE_OFFLINE', '设备离线'), ('APP_CRASH', '应用崩溃'), ('TIMEOUT', '执行超时'), ('UNKNOWN', '未知错误')], db_index=True, max_length=30, null=True, verbose_name='失败分类'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='failure_hint',
            field=models.TextField(blank=True, default='', verbose_name='失败提示'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='已重试次数'),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='self_healed',
            field=models.BooleanField(default=False, verbose_name='是否自愈'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='evidence_summary',
            field=models.TextField(blank=True, default='', verbose_name='证据摘要'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='failure_category',
            field=models.CharField(blank=True, choices=[('NETWORK_TIMEOUT', '网络超时'), ('CONNECTION_ERROR', '连接失败'), ('ASSERTION_ERROR', '断言失败'), ('LOCATOR_NOT_FOUND', '定位器未找到'), ('ELEMENT_NOT_FOUND', '元素未找到'), ('ELEMENT_NOT_INTERACTABLE', '元素不可交互'), ('AUTH_ERROR', '鉴权失败'), ('HTTP_4XX', '客户端错误(4xx)'), ('HTTP_5XX', '服务端错误(5xx)'), ('DEVICE_OFFLINE', '设备离线'), ('APP_CRASH', '应用崩溃'), ('TIMEOUT', '执行超时'), ('UNKNOWN', '未知错误')], db_index=True, max_length=30, null=True, verbose_name='失败分类'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='failure_hint',
            field=models.TextField(blank=True, default='', verbose_name='失败提示'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='已重试次数'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='self_healed',
            field=models.BooleanField(default=False, verbose_name='是否自愈'),
        ),
    ]
