# Generated by Django 4.2.7 on 2026-09-15 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='批次名称')),
                ('cases_data', models.JSONField(default=list, verbose_name='批量用例数据')),
                ('total', models.IntegerField(default=0, verbose_name='总数')),
                ('scored', models.IntegerField(default=0, verbose_name='已评分数')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(0-100)')),
                ('is_paused', models.BooleanField(default=False, verbose_name='暂停标记（worker 读到即中断）')),
                ('error_count', models.IntegerField(default=0, verbose_name='累计失败用例数')),
                ('results_buffer', models.JSONField(blank=True, default=list, verbose_name='已完成用例结果缓存（含成功/失败）')),
                ('mean_score', models.FloatField(default=0.0, verbose_name='平均分')),
                ('std_dev', models.FloatField(default=0.0, verbose_name='标准差')),
                ('safety_pass_rate', models.FloatField(default=0.0, verbose_name='安全通过率')),
                ('critical_success_rate', models.FloatField(default=0.0, verbose_name='严重成功率')),
                ('gate_zone', models.CharField(choices=[('green', '绿区(放行)'), ('yellow', '黄区(复核)'), ('red', '红区(拦截)')], default='red', max_length=10, verbose_name='门禁分区')),
                ('blocked', models.BooleanField(default=True, verbose_name='是否拦截')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败'), ('partial', '部分成功')], default='pending', max_length=15, verbose_name='状态')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Celery任务ID')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '评分批次',
                'verbose_name_plural': '评分批次',
                'db_table': 'llm_judge_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KBCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='主体名称（标准名）')),
                ('aliases', models.JSONField(default=list, verbose_name='别名列表')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='扩展信息')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '知识库主体',
                'verbose_name_plural': '知识库主体',
                'db_table': 'llm_judge_kb_company',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KBMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='指标名（标准名，如 营业收入）')),
                ('aliases', models.JSONField(default=list, verbose_name='别名列表（如 营收、收入）')),
                ('default_unit', models.CharField(blank=True, default='', max_length=20, verbose_name='默认单位')),
                ('default_tolerance', models.FloatField(default=5.0, verbose_name='默认容差（% 或绝对值）')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '知识库指标',
                'verbose_name_plural': '知识库指标',
                'db_table': 'llm_judge_kb_metric',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('domain', models.CharField(choices=[('finance', '金融领域'), ('qa', '通用问答'), ('customer_service', '客服场景'), ('custom', '自定义')], default='qa', max_length=30, verbose_name='领域')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='版本')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('scoring_weights', models.JSONField(default=dict, verbose_name='评分权重')),
                ('gate_config', models.JSONField(default=dict, verbose_name='门禁配置')),
                ('judge_config', models.JSONField(default=dict, verbose_name='Judge 配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '评分标准',
                'verbose_name_plural': '评分标准',
                'db_table': 'llm_judge_rubric',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='知识库名称')),
                ('domain', models.CharField(choices=[('finance', '金融领域'), ('qa', '通用问答'), ('customer_service', '客服场景'), ('custom', '自定义')], default='finance', max_length=30, verbose_name='领域')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'llm_judge_kb',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KBReportPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='报告期（标准名，如 2024年报）')),
                ('aliases', models.JSONField(default=list, verbose_name='别名列表（如 2024年度、2024财年）')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_periods', to='llm_judge.knowledgebase', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '知识库报告期',
                'verbose_name_plural': '知识库报告期',
                'db_table': 'llm_judge_kb_period',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KBMetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='数值')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('tolerance', models.FloatField(default=5.0, verbose_name='容差')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='llm_judge.kbcompany', verbose_name='主体')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='llm_judge.kbmetric', verbose_name='指标')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='llm_judge.kbreportperiod', verbose_name='报告期')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '指标数值',
                'verbose_name_plural': '指标数值',
                'db_table': 'llm_judge_kb_metric_value',
                'ordering': ['company', 'period', 'metric'],
            },
        ),
        migrations.AddField(
            model_name='kbmetric',
            name='kb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='llm_judge.knowledgebase', verbose_name='知识库'),
        ),
        migrations.AddField(
            model_name='kbcompany',
            name='kb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='llm_judge.knowledgebase', verbose_name='知识库'),
        ),
        migrations.CreateModel(
            name='JudgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=64, unique=True, verbose_name='请求ID')),
                ('question', models.TextField(verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
                ('ground_truth', models.JSONField(blank=True, null=True, verbose_name='参考答案')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='上下文')),
                ('auto_gt', models.BooleanField(default=False, verbose_name='是否自动匹配GT')),
                ('rule_score', models.FloatField(default=0.0, verbose_name='规则分')),
                ('llm_score', models.FloatField(default=0.0, verbose_name='LLM分')),
                ('final_score', models.FloatField(default=0.0, verbose_name='最终分')),
                ('overall_label', models.CharField(choices=[('excellent', '优秀'), ('acceptable', '合格'), ('needs_improvement', '待改进'), ('critical_failure', '严重失败')], default='needs_improvement', max_length=30, verbose_name='整体评级')),
                ('gate_zone', models.CharField(choices=[('green', '绿区(放行)'), ('yellow', '黄区(复核)'), ('red', '红区(拦截)')], default='red', max_length=10, verbose_name='门禁分区')),
                ('blocked', models.BooleanField(default=True, verbose_name='是否拦截')),
                ('rule_findings', models.JSONField(default=list, verbose_name='规则命中')),
                ('vetoed', models.BooleanField(default=False, verbose_name='是否一票否决')),
                ('veto_reasons', models.JSONField(default=list, verbose_name='否决原因')),
                ('verdict_reasoning', models.TextField(blank=True, default='', verbose_name='LLM评判理由')),
                ('verdict_dimensions', models.JSONField(default=list, verbose_name='LLM维度评分')),
                ('judge_model', models.CharField(blank=True, default='', max_length=50, verbose_name='评判模型')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='评分耗时(ms)')),
                ('cache_hit', models.BooleanField(default=False, verbose_name='是否缓存命中')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='llm_judge.judgebatch', verbose_name='所属批次')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='llm_judge.rubric', verbose_name='评分标准')),
            ],
            options={
                'verbose_name': '评分记录',
                'verbose_name_plural': '评分记录',
                'db_table': 'llm_judge_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='judgebatch',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='llm_judge.rubric', verbose_name='评分标准'),
        ),
        migrations.CreateModel(
            name='RubricRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(max_length=50, verbose_name='规则键')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('severity', models.CharField(choices=[('info', '提示'), ('warn', '警告'), ('critical', '严重')], default='warn', max_length=10, verbose_name='严重度')),
                ('is_veto', models.BooleanField(default=False, verbose_name='是否一票否决')),
                ('fallback_mode', models.CharField(choices=[('keyword', '关键词匹配'), ('regex', '正则匹配'), ('llm', 'LLM 兜底'), ('hybrid', '混合(关键词+LLM)')], default='keyword', max_length=10, verbose_name='兜底模式')),
                ('params', models.JSONField(default=dict, verbose_name='规则参数')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='llm_judge.rubric', verbose_name='评分标准')),
            ],
            options={
                'verbose_name': '评分规则',
                'verbose_name_plural': '评分规则',
                'db_table': 'llm_judge_rubric_rule',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['rubric', 'enabled'], name='llm_judge_r_rubric__40789f_idx')],
                'unique_together': {('rubric', 'rule_key')},
            },
        ),
        migrations.CreateModel(
            name='RubricDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_key', models.CharField(max_length=50, verbose_name='维度键')),
                ('name', models.CharField(max_length=100, verbose_name='维度名称')),
                ('dim_type', models.CharField(choices=[('score', '评分型(1-5)'), ('bool', '布尔型')], default='score', max_length=10, verbose_name='维度类型')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重')),
                ('anchor_text', models.JSONField(default=dict, verbose_name='评分锚点')),
                ('vetoable', models.BooleanField(default=False, verbose_name='是否可触发否决')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='llm_judge.rubric', verbose_name='评分标准')),
            ],
            options={
                'verbose_name': '评分维度',
                'verbose_name_plural': '评分维度',
                'db_table': 'llm_judge_rubric_dimension',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['rubric', 'sort_order'], name='llm_judge_r_rubric__a0d503_idx')],
                'unique_together': {('rubric', 'dim_key')},
            },
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['domain', 'is_active'], name='llm_judge_r_domain_e718ca_idx'),
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['is_default'], name='llm_judge_r_is_defa_aff768_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kbreportperiod',
            unique_together={('kb', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='kbmetricvalue',
            unique_together={('company', 'period', 'metric')},
        ),
        migrations.AlterUniqueTogether(
            name='kbmetric',
            unique_together={('kb', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='kbcompany',
            unique_together={('kb', 'name')},
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['-created_at'], name='llm_judge_r_created_cc83bc_idx'),
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['gate_zone'], name='llm_judge_r_gate_zo_88b4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['vetoed'], name='llm_judge_r_vetoed_78084b_idx'),
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['rubric', '-created_at'], name='llm_judge_r_rubric__21511c_idx'),
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['batch'], name='llm_judge_r_batch_i_312ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='judgerecord',
            index=models.Index(fields=['final_score'], name='llm_judge_r_final_s_3df443_idx'),
        ),
        migrations.AddIndex(
            model_name='judgebatch',
            index=models.Index(fields=['-created_at'], name='llm_judge_b_created_31b11a_idx'),
        ),
        migrations.AddIndex(
            model_name='judgebatch',
            index=models.Index(fields=['status'], name='llm_judge_b_status_7708b5_idx'),
        ),
        migrations.AddIndex(
            model_name='judgebatch',
            index=models.Index(fields=['rubric'], name='llm_judge_b_rubric__00c567_idx'),
        ),
    ]
