# Generated by Django 4.2.7 on 2026-07-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ui_settings',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='界面偏好'),
        ),
    ]
