# Generated by Django 4.2.7 on 2026-07-17 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_rename_prj_module_idx_project_map_project_772106_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(max_length=50, unique=True, verbose_name='执行ID')),
                ('status', models.CharField(choices=[('QUEUED', '排队中'), ('RUNNING', '执行中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('CANCELLED', '已取消')], default='QUEUED', max_length=16, verbose_name='状态')),
                ('thread_count', models.PositiveIntegerField(default=10, verbose_name='线程数')),
                ('ramp_up', models.PositiveIntegerField(default=5, verbose_name='Ramp-Up(秒)')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='持续时间(秒)')),
                ('realtime_enabled', models.BooleanField(default=False, verbose_name='启用实时报告')),
                ('jmx_path', models.CharField(blank=True, default='', max_length=500, verbose_name='JMX 路径')),
                ('jtl_path', models.CharField(blank=True, default='', max_length=500, verbose_name='JTL 路径')),
                ('jmeter_log', models.TextField(blank=True, default='', verbose_name='JMeter 日志')),
                ('report_path', models.CharField(blank=True, default='', max_length=500, verbose_name='HTML报告路径')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '性能执行记录',
                'verbose_name_plural': '性能执行记录',
                'db_table': 'perf_execution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_samples', models.PositiveIntegerField(default=0, verbose_name='总样本数')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='错误数')),
                ('error_rate', models.FloatField(default=0.0, verbose_name='错误率(%)')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='平均响应时间(ms)')),
                ('min_response_time', models.FloatField(default=0.0, verbose_name='最小响应时间(ms)')),
                ('max_response_time', models.FloatField(default=0.0, verbose_name='最大响应时间(ms)')),
                ('p90', models.FloatField(default=0.0, verbose_name='P90(ms)')),
                ('p95', models.FloatField(default=0.0, verbose_name='P95(ms)')),
                ('p99', models.FloatField(default=0.0, verbose_name='P99(ms)')),
                ('throughput', models.FloatField(default=0.0, verbose_name='吞吐量(req/s)')),
                ('data_received', models.BigIntegerField(default=0, verbose_name='接收字节')),
                ('data_sent', models.BigIntegerField(default=0, verbose_name='发送字节')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='performance_testing.performanceexecution', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': '性能汇总',
                'verbose_name_plural': '性能汇总',
                'db_table': 'perf_summary',
            },
        ),
        migrations.CreateModel(
            name='PerformanceScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='脚本名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('script_type', models.CharField(choices=[('ONLINE', '在线编排'), ('JMX_UPLOAD', 'JMX 导入')], default='ONLINE', max_length=16, verbose_name='脚本模式')),
                ('jmx_config', models.JSONField(blank=True, default=dict, verbose_name='在线编排配置')),
                ('jmx_file', models.FileField(blank=True, null=True, upload_to='performance/jmx/', verbose_name='JMX 文件')),
                ('thread_count', models.PositiveIntegerField(default=10, verbose_name='线程数')),
                ('ramp_up', models.PositiveIntegerField(default=5, verbose_name='Ramp-Up(秒)')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='持续时间(秒)')),
                ('realtime_enabled', models.BooleanField(default=False, verbose_name='启用实时报告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_scripts', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '性能测试脚本',
                'verbose_name_plural': '性能测试脚本',
                'db_table': 'perf_script',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='performanceexecution',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='performance_testing.performancescript', verbose_name='脚本'),
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_label', models.CharField(max_length=500, verbose_name='请求名称')),
                ('sample_count', models.PositiveIntegerField(default=0, verbose_name='样本数')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='错误数')),
                ('error_rate', models.FloatField(default=0.0, verbose_name='错误率(%)')),
                ('avg', models.FloatField(default=0.0, verbose_name='平均(ms)')),
                ('min', models.FloatField(default=0.0, verbose_name='最小(ms)')),
                ('max', models.FloatField(default=0.0, verbose_name='最大(ms)')),
                ('p90', models.FloatField(default=0.0, verbose_name='P90(ms)')),
                ('p95', models.FloatField(default=0.0, verbose_name='P95(ms)')),
                ('p99', models.FloatField(default=0.0, verbose_name='P99(ms)')),
                ('throughput', models.FloatField(default=0.0, verbose_name='吞吐量(req/s)')),
                ('timeline', models.JSONField(blank=True, default=list, verbose_name='10秒时间线')),
                ('top_errors', models.JSONField(blank=True, default=list, verbose_name='Top20错误')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='performance_testing.performanceexecution', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': '性能指标',
                'verbose_name_plural': '性能指标',
                'db_table': 'perf_metric',
                'indexes': [models.Index(fields=['execution'], name='perf_metric_executi_8b6334_idx')],
            },
        ),
    ]
