# Generated by Django 4.2.7 on 2026-09-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0009_performanceconfig_monitor_targets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceexecution',
            name='sla_detail',
            field=models.JSONField(blank=True, default=list, verbose_name='SLA逐项判定'),
        ),
        migrations.AddField(
            model_name='performanceexecution',
            name='sla_result',
            field=models.CharField(choices=[('PASSED', '通过'), ('FAILED', '未通过'), ('NOT_EVALUATED', '未评估')], default='NOT_EVALUATED', max_length=20, verbose_name='SLA判定结果'),
        ),
        migrations.AddField(
            model_name='performanceexecution',
            name='verdict',
            field=models.CharField(choices=[('PASSED', '通过'), ('FAILED', '未通过'), ('NOT_EVALUATED', '未评估')], default='NOT_EVALUATED', max_length=20, verbose_name='验收判定'),
        ),
        migrations.AddField(
            model_name='performanceexecution',
            name='verdict_details',
            field=models.JSONField(blank=True, default=list, verbose_name='验收明细'),
        ),
        migrations.AddField(
            model_name='performancescript',
            name='perf_targets',
            field=models.JSONField(blank=True, default=dict, verbose_name='验收目标'),
        ),
        migrations.AddField(
            model_name='performancescript',
            name='sla_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='SLA 阈值配置'),
        ),
    ]
