# Generated by Django 4.2.7 on 2026-09-15 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance_testing', '0010_performanceexecution_sla_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='基线指标快照')),
                ('tolerance', models.JSONField(blank=True, default=dict, verbose_name='容忍度(JSON:{rt_degrade_pct,tps_degrade_pct})')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baselines', to='performance_testing.performanceexecution', verbose_name='基线来源执行')),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='performance_testing.performancescript', verbose_name='脚本')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_baselines', to=settings.AUTH_USER_MODEL, verbose_name='设置人')),
            ],
            options={
                'verbose_name': '性能基线',
                'verbose_name_plural': '性能基线',
                'db_table': 'perf_baseline',
                'ordering': ['-updated_at'],
            },
        ),
    ]
