# Generated by Django 4.2.7 on 2026-09-15 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance_testing', '0011_performancebaseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceComparisonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('execution_ids', models.JSONField(default=list, verbose_name='参与对比的执行ID列表')),
                ('reference_execution_id', models.IntegerField(blank=True, null=True, verbose_name='基准执行ID')),
                ('snapshot', models.JSONField(default=dict, verbose_name='对照快照')),
                ('ai_analysis', models.TextField(blank=True, null=True, verbose_name='AI对照分析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_comparison_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_reports', to='performance_testing.performancescript', verbose_name='脚本')),
            ],
            options={
                'verbose_name': '性能对照报告',
                'verbose_name_plural': '性能对照报告',
                'db_table': 'perf_comparison_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
