# Generated by Django 4.2.7 on 2026-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0012_performancecomparisonreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceexecution',
            name='share_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='分享过期时间'),
        ),
        migrations.AddField(
            model_name='performanceexecution',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='分享令牌'),
        ),
    ]
