# Generated by Django 4.2.7 on 2026-09-15 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_prj_module_idx_project_map_project_772106_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance_testing', '0013_performanceexecution_share_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceexecution',
            name='config_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='生效配置快照'),
        ),
        migrations.CreateModel(
            name='PerformanceEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='环境名称')),
                ('scope', models.CharField(choices=[('GLOBAL', '全局环境'), ('PROJECT', '项目环境')], default='PROJECT', max_length=10, verbose_name='作用域')),
                ('base_url', models.CharField(blank=True, default='', max_length=500, verbose_name='基础地址')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='全局请求头')),
                ('verify_ssl', models.BooleanField(default=False, verbose_name='校验 SSL 证书')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='环境变量')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perf_environments', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perf_environments', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '压测环境',
                'verbose_name_plural': '压测环境',
                'db_table': 'perf_environment',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='performanceexecution',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='performance_testing.performanceenvironment', verbose_name='执行环境'),
        ),
    ]
