# Generated by Django 4.2.7 on 2026-09-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0014_performanceexecution_config_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancescript',
            name='engine',
            field=models.CharField(choices=[('JMETER', 'JMeter'), ('BUILTIN', '内置引擎'), ('LOCUST', 'Locust')], default='JMETER', max_length=16, verbose_name='压测引擎'),
        ),
    ]
