# Generated by Django 4.2.7 on 2026-07-20 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0023_alter_testcaseskill_skill_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0005_difyconfig_invoke_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HermesConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hermes_conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Hermes 会话',
                'verbose_name_plural': 'Hermes 会话',
                'db_table': 'hermes_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HermesMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(blank=True, default='', verbose_name='消息内容')),
                ('tool_calls', models.JSONField(blank=True, default=list, verbose_name='工具调用')),
                ('thought_text', models.TextField(blank=True, default='', verbose_name='思考过程')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.hermesconversation', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'Hermes 消息',
                'verbose_name_plural': 'Hermes 消息',
                'db_table': 'hermes_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HermesAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认配置', max_length=100, verbose_name='配置名称')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='覆盖默认 Hermes 系统提示词，为空则使用内置默认', verbose_name='系统提示词')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500, verbose_name='数字人模型 URL')),
                ('tts_enabled', models.BooleanField(default=True, verbose_name='TTS 朗读')),
                ('active_skills', models.JSONField(blank=True, default=list, verbose_name='默认启用技能 ID 列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hermes_configs', to='requirement_analysis.aimodelconfig', verbose_name='AI 模型配置')),
            ],
            options={
                'verbose_name': '数字人配置',
                'verbose_name_plural': '数字人配置',
                'db_table': 'hermes_agent_configs',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
