# Generated by Django 4.2.7 on 2026-07-20 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_hermesconversation_hermesmessage_hermesagentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='hermesmessage',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='用户上传的图片信息，[{id, url, name}]', verbose_name='图片列表'),
        ),
        migrations.CreateModel(
            name='HermesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hermes/%Y/%m/', verbose_name='图片文件')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='原文件名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assistant.hermesconversation', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'Hermes 图片',
                'verbose_name_plural': 'Hermes 图片',
                'db_table': 'hermes_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
