# Generated by Django 4.2.7 on 2026-01-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ui_automation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uinotificationlog',
            name='task_type',
            field=models.CharField(blank=True, help_text='发送通知时的任务类型', max_length=20, null=True, verbose_name='任务类型快照'),
        ),
        migrations.AlterField(
            model_name='aicase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='aiexecutionrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='uitasknotificationsetting',
            name='notification_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_task_notification_settings', to='core.unifiednotificationconfig', verbose_name='通知配置'),
        ),
        migrations.DeleteModel(
            name='UiNotificationConfig',
        ),
    ]
