# Generated by Django 4.2.7 on 2026-02-27 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def drop_columns_if_exist(apps, schema_editor):
    """兼容旧版 MySQL：先查 information_schema 再按需 DROP COLUMN，避免 1091/1064。"""
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        def column_exists(table, column):
            cursor.execute(
                """
                SELECT 1 FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s
                """,
                [table, column],
            )
            return cursor.fetchone() is not None

        def drop_foreign_keys(table, column):
            """删列前必须先摘掉该列上的外键，否则 MySQL 报 1828
            （Cannot drop column ... needed in a foreign key constraint）。

            全新库上 ai_suite_id 的外键仍然存在，就是靠这一步才能删掉。
            """
            cursor.execute(
                """
                SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE
                WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s
                  AND REFERENCED_TABLE_NAME IS NOT NULL
                """,
                [table, column],
            )
            for (constraint_name,) in cursor.fetchall():
                cursor.execute("ALTER TABLE %s DROP FOREIGN KEY %s" % (
                    schema_editor.quote_name(table),
                    schema_editor.quote_name(constraint_name),
                ))

        drops = [
            ("ui_ai_execution_records", "ai_suite_id"),
            ("ui_ai_execution_records", "execution_history"),
            ("ui_ai_execution_records", "model_info"),
            ("ui_ai_execution_records", "performance_metrics"),
            ("ui_ai_execution_records", "suite_run_id"),
            ("ui_test_executions", "suite_run_id"),
            ("ui_notification_logs", "task_type"),
        ]
        for table, column in drops:
            if column_exists(table, column):
                drop_foreign_keys(table, column)
                cursor.execute("ALTER TABLE %s DROP COLUMN %s" % (
                    schema_editor.quote_name(table),
                    schema_editor.quote_name(column),
                ))


def create_ui_notification_configs_if_not_exists(apps, schema_editor):
    """若表已存在（迁移曾部分执行），则跳过建表，避免 1050。

    注意：这段裸 SQL 必须按**本项目实际配置**推导，不能写死。历史版本写死了
    ``created_by_id int ... REFERENCES auth_user (id)``：在「表已存在」的库上会被
    上面的早退分支跳过而看不出问题，一旦在全新库上真正执行，就会报 1824
    （auth_user 不存在，本项目用户表是 users_user）；FK 列类型也必须与用户表主键
    一致（本项目 BigAutoField → bigint），否则报 3780。
    """
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        cursor.execute(
            """
            SELECT 1 FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ui_notification_configs'
            """
        )
        if cursor.fetchone() is not None:
            return

        user_model = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
        user_table = schema_editor.quote_name(user_model._meta.db_table)
        user_pk_column = schema_editor.quote_name(user_model._meta.pk.column)
        # BigAutoField/AutoField → bigint/int，保证与用户表主键类型一致（否则报 3780）
        pk_type = "bigint" if user_model._meta.pk.get_internal_type() == "BigAutoField" else "int"

        cursor.execute(
            """
            CREATE TABLE ui_notification_configs (
                id bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
                name varchar(100) NOT NULL,
                config_type varchar(20) NOT NULL DEFAULT 'webhook_feishu',
                webhook_bots json DEFAULT NULL,
                is_default tinyint(1) NOT NULL DEFAULT 0,
                is_active tinyint(1) NOT NULL DEFAULT 1,
                created_at datetime(6) NOT NULL,
                updated_at datetime(6) NOT NULL,
                created_by_id %s NOT NULL,
                CONSTRAINT ui_notification_configs_created_by_id_fk
                    FOREIGN KEY (created_by_id) REFERENCES %s (%s)
            )
            """ % (pk_type, user_table, user_pk_column)
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0008_alter_aiexecutionrecord_execution_mode'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_columns_if_exist, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='aiexecutionrecord',
                    name='ai_suite',
                ),
                migrations.RemoveField(
                    model_name='aiexecutionrecord',
                    name='execution_history',
                ),
                migrations.RemoveField(
                    model_name='aiexecutionrecord',
                    name='model_info',
                ),
                migrations.RemoveField(
                    model_name='aiexecutionrecord',
                    name='performance_metrics',
                ),
                migrations.RemoveField(
                    model_name='aiexecutionrecord',
                    name='suite_run_id',
                ),
                migrations.RemoveField(
                    model_name='testexecution',
                    name='suite_run_id',
                ),
                migrations.RemoveField(
                    model_name='uinotificationlog',
                    name='task_type',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='aiexecutionrecord',
            name='execution_mode',
            field=models.CharField(choices=[('text', '文本模式')], default='text', max_length=20, verbose_name='执行模式'),
        ),
        migrations.AlterField(
            model_name='aiexecutionrecord',
            name='status',
            field=models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='ainotificationlog',
            name='notification_type',
            field=models.CharField(choices=[('task_execution', '定时任务执行'), ('test_suite_execution', '测试套件执行'), ('test_case_execution', '测试用例执行'), ('system_alert', '系统警告'), ('manual', '手动通知')], max_length=50, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='ainotificationlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui_automation.aischeduledtask', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='ainotificationlog',
            name='task_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='execution_mode',
            field=models.CharField(blank=True, default='text', max_length=20, verbose_name='执行模式'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='failed_runs',
            field=models.IntegerField(default=0, verbose_name='失败次数'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='last_result',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='最后执行结果'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='notification_type',
            field=models.CharField(blank=True, default='webhook', max_length=20, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='notify_on_failure',
            field=models.BooleanField(default=True, verbose_name='失败时通知'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='notify_on_success',
            field=models.BooleanField(default=True, verbose_name='成功时通知'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '启用'), ('PAUSED', '暂停'), ('DISABLED', '禁用')], default='ACTIVE', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='successful_runs',
            field=models.IntegerField(default=0, verbose_name='成功次数'),
        ),
        migrations.AlterField(
            model_name='aisuite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suites', to='ui_automation.uiproject', verbose_name='关联项目'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_ui_notification_configs_if_not_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
            name='UiNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用于标识该通知配置的名称', max_length=100, verbose_name='配置名称')),
                ('config_type', models.CharField(choices=[('webhook_feishu', '飞书机器人'), ('webhook_wechat', '企业微信机器人'), ('webhook_dingtalk', '钉钉机器人')], default='webhook_feishu', max_length=20, verbose_name='配置类型')),
                ('webhook_bots', models.JSONField(blank=True, default=dict, help_text='飞书、企业微信、钉钉机器人配置', null=True, verbose_name='Webhook机器人配置')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'UI通知配置',
                'verbose_name_plural': 'UI通知配置',
                'db_table': 'ui_notification_configs',
                'ordering': ['-created_at'],
            },
        ),
            ],
        ),
        migrations.RunSQL(
            "UPDATE ui_task_notification_settings SET notification_config_id = NULL",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='uitasknotificationsetting',
            name='notification_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_config', to='ui_automation.uinotificationconfig', verbose_name='通知配置'),
        ),
        migrations.AddIndex(
            model_name='uinotificationconfig',
            index=models.Index(fields=['config_type'], name='ui_notifica_config__8a3d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='uinotificationconfig',
            index=models.Index(fields=['is_default'], name='ui_notifica_is_defa_c1f05e_idx'),
        ),
        migrations.AddIndex(
            model_name='uinotificationconfig',
            index=models.Index(fields=['created_by'], name='ui_notifica_created_6e0b99_idx'),
        ),
    ]
