# Generated by Django 4.2.7 on 2026-03-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0011_fill_null_created_by_then_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiexecutionrecord',
            name='execution_mode',
            field=models.CharField(choices=[('text', '文本模式'), ('vision', '视觉模式')], default='text', max_length=20, verbose_name='执行模式'),
        ),
        migrations.AlterField(
            model_name='ainotificationlog',
            name='task_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='任务类型快照'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='execution_mode',
            field=models.CharField(default='text', max_length=20, verbose_name='执行模式'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='failed_runs',
            field=models.IntegerField(default=0, verbose_name='失败运行次数'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='last_result',
            field=models.JSONField(default=dict, verbose_name='最后执行结果'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='notification_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='notify_on_failure',
            field=models.BooleanField(default=False, verbose_name='失败时通知'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='notify_on_success',
            field=models.BooleanField(default=False, verbose_name='成功时通知'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '启用'), ('PAUSED', '暂停'), ('DISABLED', '禁用')], default='ACTIVE', max_length=20, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='aischeduledtask',
            name='successful_runs',
            field=models.IntegerField(default=0, verbose_name='成功运行次数'),
        ),
        migrations.AlterField(
            model_name='uischeduledtask',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
    ]
