# Generated by Django 4.2.7 on 2026-03-02 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0012_alter_aiexecutionrecord_execution_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='aiexecutionrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_automation.uiproject', verbose_name='所属项目'),
        ),
    ]
