# Generated by Django 4.2.7 on 2026-07-27 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0014_uiproject_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiScriptGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_testcase_id', models.IntegerField(verbose_name='源用例ID(testcases.TestCase)')),
                ('source_testcase_title', models.CharField(blank=True, max_length=500, verbose_name='源用例标题')),
                ('base_url', models.CharField(max_length=500, verbose_name='被测系统地址')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '全部通过'), ('partial', '部分通过'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('elements_captured', models.IntegerField(default=0, verbose_name='抓取元素数')),
                ('steps_total', models.IntegerField(default=0, verbose_name='步骤总数')),
                ('steps_passed', models.IntegerField(default=0, verbose_name='验证通过步骤数')),
                ('progress_log', models.TextField(blank=True, default='', verbose_name='进度日志')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ai_execution_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ui_automation.aiexecutionrecord', verbose_name='智能体执行记录')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('generated_script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ui_automation.testscript', verbose_name='生成的脚本')),
                ('ui_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_generations', to='ui_automation.uiproject', verbose_name='目标UI项目')),
            ],
            options={
                'verbose_name': '用例脚本生成',
                'verbose_name_plural': '用例脚本生成',
                'db_table': 'ui_script_generations',
                'ordering': ['-created_at'],
            },
        ),
    ]
