# Generated by Django 4.2.7 on 2026-07-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0015_uiscriptgeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiscriptgeneration',
            name='ui_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ui_automation.testsuite', verbose_name='生成的套件'),
        ),
    ]
