# Generated by Django 4.2.7 on 2026-07-27 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0016_uiscriptgeneration_ui_suite'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiscriptgeneration',
            name='suite_exec_pass_rate',
            field=models.FloatField(default=0, verbose_name='套件执行通过率'),
        ),
        migrations.AddField(
            model_name='uiscriptgeneration',
            name='suite_exec_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='套件执行状态'),
        ),
        migrations.AddField(
            model_name='uiscriptgeneration',
            name='suite_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ui_automation.testexecution', verbose_name='套件执行记录'),
        ),
    ]
