# Generated by Django 4.2.7 on 2026-07-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0018_uiscriptgeneration_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiscriptgeneration',
            name='generated_test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ui_automation.testcase', verbose_name='生成的UI用例'),
        ),
        migrations.AlterField(
            model_name='uiscriptgeneration',
            name='generated_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ui_automation.testscript', verbose_name='生成的脚本（兼容旧数据）'),
        ),
    ]
