# Generated by Django 4.2.7 on 2026-07-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0019_uiscriptgeneration_generated_test_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiscriptgeneration',
            name='playwright_code',
            field=models.TextField(blank=True, default='', verbose_name='Playwright 代码（仅参考）'),
        ),
    ]
