# Generated by Django 4.2.7 on 2026-07-27 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0021_testcaseexecution_evidence_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='cloned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='克隆时间'),
        ),
        migrations.AddField(
            model_name='element',
            name='cloned_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='克隆来源ID'),
        ),
        migrations.AddField(
            model_name='pageobject',
            name='cloned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='克隆时间'),
        ),
        migrations.AddField(
            model_name='pageobject',
            name='cloned_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='克隆来源ID'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='cloned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='克隆时间'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='cloned_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='克隆来源ID'),
        ),
        migrations.AddField(
            model_name='testscript',
            name='cloned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='克隆时间'),
        ),
        migrations.AddField(
            model_name='testscript',
            name='cloned_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='克隆来源ID'),
        ),
        migrations.CreateModel(
            name='SharedStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='步骤名称')),
                ('description', models.TextField(blank=True, verbose_name='步骤描述')),
                ('action_type', models.CharField(choices=[('CLICK', '点击'), ('INPUT', '输入'), ('SELECT', '选择'), ('VERIFY', '验证'), ('WAIT', '等待'), ('HOVER', '悬停'), ('SCROLL', '滚动'), ('NAVIGATE', '导航'), ('SCREENSHOT', '截图'), ('SWITCH_TAB', '切换标签页'), ('CUSTOM', '自定义')], max_length=20, verbose_name='操作类型')),
                ('action_params', models.JSONField(blank=True, null=True, verbose_name='操作参数')),
                ('expected_result', models.CharField(blank=True, max_length=500, verbose_name='预期结果')),
                ('wait_before', models.IntegerField(default=0, verbose_name='执行前等待(毫秒)')),
                ('wait_after', models.IntegerField(default=0, verbose_name='执行后等待(毫秒)')),
                ('usage_count', models.IntegerField(default=0, verbose_name='被引用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cloned_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='克隆来源ID')),
                ('cloned_at', models.DateTimeField(blank=True, null=True, verbose_name='克隆时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_steps', to='ui_automation.uiproject', verbose_name='所属项目')),
                ('target_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui_automation.element', verbose_name='目标元素')),
            ],
            options={
                'verbose_name': '公共步骤',
                'verbose_name_plural': '公共步骤',
                'db_table': 'ui_shared_steps',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='scriptstep',
            name='shared_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages_in_script', to='ui_automation.sharedstep', verbose_name='引用的公共步骤'),
        ),
        migrations.AddField(
            model_name='testcasestep',
            name='shared_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages_in_case', to='ui_automation.sharedstep', verbose_name='引用的公共步骤'),
        ),
    ]
