# Generated by Django 4.2.7 on 2026-08-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0022_element_cloned_at_element_cloned_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscript',
            name='assertions',
            field=models.JSONField(blank=True, default=list, help_text='脚本级后置断言，用于校验业务结果是否真落库。示例: [{"type":"record_count","model":"app_label.Model","filter":{...},"expect_delta":1},{"type":"page_contains","text":"创建成功"}]', null=True, verbose_name='后置业务断言'),
        ),
    ]
