# Generated by Django 4.2.7 on 2026-08-14 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0023_testscript_assertions'),
    ]

    operations = [
        migrations.AddField(
            model_name='uischeduledtask',
            name='record_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='ui_automation.uiscriptgeneration', verbose_name='录制脚本'),
        ),
        migrations.AlterField(
            model_name='uischeduledtask',
            name='task_type',
            field=models.CharField(choices=[('TEST_SUITE', '测试套件执行'), ('TEST_CASE', '测试用例执行'), ('RECORD_SCRIPT', '录制脚本执行')], max_length=20, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='uiscriptgeneration',
            name='source_testcase_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='源用例ID(testcases.TestCase)，录制脚本可留空'),
        ),
    ]
