# Generated by Django 4.2.7 on 2026-08-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0024_record_script_and_nullable_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiscriptgeneration',
            name='ui_project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='script_generations',
                to='ui_automation.uiproject',
                verbose_name='目标UI项目',
            ),
        ),
    ]
