# Generated by Django 4.2.7 on 2026-07-06 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KgEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_key', models.CharField(db_index=True, max_length=160, unique=True, verbose_name='实体键')),
                ('entity_type', models.CharField(db_index=True, max_length=48, verbose_name='实体类型')),
                ('ref_app', models.CharField(blank=True, default='', max_length=64, verbose_name='来源 App')),
                ('ref_id', models.CharField(blank=True, default='', max_length=128, verbose_name='来源 ID')),
                ('project_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='项目 ID')),
                ('label', models.CharField(blank=True, default='', max_length=500, verbose_name='展示名')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='扩展属性')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '图谱实体',
                'verbose_name_plural': '图谱实体',
                'db_table': 'kg_entity',
                'indexes': [models.Index(fields=['entity_type', 'project_id'], name='kg_entity_entity__f109ed_idx'), models.Index(fields=['ref_app', 'ref_id'], name='kg_entity_ref_app_890ac1_idx')],
            },
        ),
        migrations.CreateModel(
            name='KgEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(db_index=True, max_length=32, verbose_name='关系类型')),
                ('project_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='项目 ID')),
                ('source', models.CharField(default='system', max_length=16, verbose_name='来源')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='置信度')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kg_edges_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='knowledge_graph.kgentity', verbose_name='目标节点')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='knowledge_graph.kgentity', verbose_name='源节点')),
            ],
            options={
                'verbose_name': '图谱边',
                'verbose_name_plural': '图谱边',
                'db_table': 'kg_edge',
                'indexes': [models.Index(fields=['relation_type', 'project_id'], name='kg_edge_relatio_77b4ae_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='kgedge',
            constraint=models.UniqueConstraint(fields=('src', 'dst', 'relation_type'), name='uniq_kg_edge_src_dst_rel'),
        ),
    ]
