# Generated by Django 4.2.7 on 2026-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0003_kgedge_confidence_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgedge',
            name='confidence_level',
            field=models.CharField(blank=True, choices=[('EXTRACTED', '字面提取'), ('INFERRED', '推断'), ('AMBIGUOUS', '歧义')], db_index=True, max_length=16, null=True, verbose_name='置信度等级'),
        ),
        migrations.AlterField(
            model_name='kgedge',
            name='dataset_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='所属知识库ID'),
        ),
        migrations.AlterField(
            model_name='kgentity',
            name='dataset_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='来源知识库ID'),
        ),
    ]
