# Generated by Django 4.2.7 on 2026-07-23 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='渠道名称')),
                ('type', models.CharField(choices=[('DINGTALK', '钉钉'), ('WECOM', '企业微信'), ('EMAIL', '邮件')], max_length=20, verbose_name='渠道类型')),
                ('config', models.JSONField(default=dict, verbose_name='渠道配置')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_channels', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '通知渠道',
                'verbose_name_plural': '通知渠道',
                'db_table': 'monitor_channels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='目标名称')),
                ('type', models.CharField(choices=[('LOGIN', '登录可用性'), ('HTTP', '接口存活'), ('ONLINE', '在线率'), ('DOCKER', '容器状态'), ('SL651', '遥测链路')], max_length=20, verbose_name='探测类型')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='请求方法')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='主机')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口')),
                ('check_config', models.JSONField(default=dict, verbose_name='探测配置')),
                ('interval_seconds', models.IntegerField(default=60, verbose_name='轮询间隔(秒)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('status', models.CharField(choices=[('UP', '正常'), ('DOWN', '异常'), ('UNKNOWN', '未知')], default='UNKNOWN', max_length=10, verbose_name='当前状态')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='最近检测时间')),
                ('consecutive_failures', models.IntegerField(default=0, verbose_name='连续失败次数')),
                ('next_check_at', models.DateTimeField(blank=True, null=True, verbose_name='下次检测时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_targets', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('notify_channels', models.ManyToManyField(blank=True, related_name='targets', to='monitor.notificationchannel', verbose_name='通知渠道')),
            ],
            options={
                'verbose_name': '监控目标',
                'verbose_name_plural': '监控目标',
                'db_table': 'monitor_targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CRITICAL', '严重'), ('WARNING', '警告')], default='CRITICAL', max_length=20, verbose_name='级别')),
                ('message', models.TextField(verbose_name='告警内容')),
                ('status', models.CharField(choices=[('FIRING', '告警中'), ('ACKED', '已认领'), ('RESOLVED', '已恢复')], default='FIRING', max_length=20, verbose_name='状态')),
                ('first_triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='首次触发')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='最近触发')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='认领时间')),
                ('send_detail', models.JSONField(default=list, verbose_name='发送结果')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_alerts_acked', to=settings.AUTH_USER_MODEL, verbose_name='认领人')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.monitortarget', verbose_name='监控目标')),
            ],
            options={
                'verbose_name': '告警记录',
                'verbose_name_plural': '告警记录',
                'db_table': 'monitor_alerts',
                'ordering': ['-last_triggered_at', '-first_triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UP', '正常'), ('DOWN', '异常'), ('UNKNOWN', '未知')], default='UNKNOWN', max_length=10, verbose_name='结果')),
                ('latency_ms', models.IntegerField(blank=True, null=True, verbose_name='延迟(ms)')),
                ('http_status', models.IntegerField(blank=True, null=True, verbose_name='HTTP状态码')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('detail', models.JSONField(default=dict, verbose_name='响应摘要')),
                ('triggered_alert', models.BooleanField(default=False, verbose_name='是否触发告警')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitor.monitortarget', verbose_name='监控目标')),
            ],
            options={
                'verbose_name': '探测记录',
                'verbose_name_plural': '探测记录',
                'db_table': 'monitor_check_logs',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['target', 'checked_at'], name='monitor_che_target__5252d4_idx')],
            },
        ),
    ]
