# Generated by Django 4.2.7 on 2026-07-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortarget',
            name='alert_threshold',
            field=models.IntegerField(default=3, verbose_name='告警阈值(连续失败次数)'),
        ),
    ]
