# Generated by Django 4.2.7 on 2026-07-23 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0002_monitortarget_alert_threshold'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='alertevent',
            table_comment='告警记录',
        ),
        migrations.AlterModelTableComment(
            name='monitorchecklog',
            table_comment='探测记录',
        ),
        migrations.AlterModelTableComment(
            name='monitortarget',
            table_comment='监控目标',
        ),
        migrations.AlterModelTableComment(
            name='notificationchannel',
            table_comment='通知渠道',
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, db_comment='认领时间', null=True, verbose_name='认领时间'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, db_comment='认领人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_alerts_acked', to=settings.AUTH_USER_MODEL, verbose_name='认领人'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='first_triggered_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='首次触发', verbose_name='首次触发'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, db_comment='最近触发', null=True, verbose_name='最近触发'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='level',
            field=models.CharField(choices=[('CRITICAL', '严重'), ('WARNING', '警告')], db_comment='级别', default='CRITICAL', max_length=20, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='message',
            field=models.TextField(db_comment='告警内容', verbose_name='告警内容'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_comment='恢复时间', null=True, verbose_name='恢复时间'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='send_detail',
            field=models.JSONField(db_comment='发送结果', default=list, verbose_name='发送结果'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='status',
            field=models.CharField(choices=[('FIRING', '告警中'), ('ACKED', '已认领'), ('RESOLVED', '已恢复')], db_comment='状态', default='FIRING', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='target',
            field=models.ForeignKey(db_comment='监控目标', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitor.monitortarget', verbose_name='监控目标'),
        ),
        migrations.AlterField(
            model_name='monitorchecklog',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='检测时间', verbose_name='检测时间'),
        ),
        migrations.AlterField(
            model_name='monitorchecklog',
            name='detail',
            field=models.JSONField(db_comment='响应摘要', default=dict, verbose_name='响应摘要'),
        ),
        migrations.AlterField(
            model_name='monitorchecklog',
            name='error_message',
            field=models.TextField(blank=True, db_comment='错误信息', verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='monitorchecklog',
            name='http_status',
            field=models.IntegerField(blank=True, db_comment='HTTP状态码', null=True, verbose_name='HTTP状态码'),
        ),
        migrations.AlterField(
            model_name='monitorchecklog',
            name='latency_ms',
            field=models.IntegerField(blank=True, db_comment='延迟(ms)', null=True, verbose_name='延迟(ms)'),
        ),
        migrations.AlterField(
            model_name='monitorchecklog',
            name='status',
            field=models.CharField(choices=[('UP', '正常'), ('DOWN', '异常'), ('UNKNOWN', '未知')], db_comment='结果', default='UNKNOWN', max_length=10, verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='monitorchecklog',
            name='target',
            field=models.ForeignKey(db_comment='监控目标', on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitor.monitortarget', verbose_name='监控目标'),
        ),
        migrations.AlterField(
            model_name='monitorchecklog',
            name='triggered_alert',
            field=models.BooleanField(db_comment='是否触发告警', default=False, verbose_name='是否触发告警'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='alert_threshold',
            field=models.IntegerField(db_comment='告警阈值(连续失败次数)', default=3, verbose_name='告警阈值(连续失败次数)'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='check_config',
            field=models.JSONField(db_comment='探测配置', default=dict, verbose_name='探测配置'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='consecutive_failures',
            field=models.IntegerField(db_comment='连续失败次数', default=0, verbose_name='连续失败次数'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='created_by',
            field=models.ForeignKey(blank=True, db_comment='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_targets', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='enabled',
            field=models.BooleanField(db_comment='启用', default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='host',
            field=models.CharField(blank=True, db_comment='主机', max_length=200, verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='interval_seconds',
            field=models.IntegerField(db_comment='轮询间隔(秒)', default=60, verbose_name='轮询间隔(秒)'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='last_check_at',
            field=models.DateTimeField(blank=True, db_comment='最近检测时间', null=True, verbose_name='最近检测时间'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='method',
            field=models.CharField(db_comment='请求方法', default='GET', max_length=10, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='name',
            field=models.CharField(db_comment='目标名称', max_length=200, unique=True, verbose_name='目标名称'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='next_check_at',
            field=models.DateTimeField(blank=True, db_comment='下次检测时间', null=True, verbose_name='下次检测时间'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='port',
            field=models.IntegerField(blank=True, db_comment='端口', null=True, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='status',
            field=models.CharField(choices=[('UP', '正常'), ('DOWN', '异常'), ('UNKNOWN', '未知')], db_comment='当前状态', default='UNKNOWN', max_length=10, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='type',
            field=models.CharField(choices=[('LOGIN', '登录可用性'), ('HTTP', '接口存活'), ('ONLINE', '在线率'), ('DOCKER', '容器状态'), ('SL651', '遥测链路')], db_comment='探测类型', max_length=20, verbose_name='探测类型'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='url',
            field=models.CharField(blank=True, db_comment='URL', max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='config',
            field=models.JSONField(db_comment='渠道配置', default=dict, verbose_name='渠道配置'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='created_by',
            field=models.ForeignKey(blank=True, db_comment='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_channels', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='enabled',
            field=models.BooleanField(db_comment='启用', default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='name',
            field=models.CharField(db_comment='渠道名称', max_length=100, unique=True, verbose_name='渠道名称'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='type',
            field=models.CharField(choices=[('DINGTALK', '钉钉'), ('WECOM', '企业微信'), ('EMAIL', '邮件')], db_comment='渠道类型', max_length=20, verbose_name='渠道类型'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
    ]
