# Generated by Django 4.2.7 on 2026-07-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_alertevent_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, db_comment='最近通知时间', null=True, verbose_name='最近通知时间'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='notify_count',
            field=models.IntegerField(db_comment='已通知次数', default=0, verbose_name='已通知次数'),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='alert_repeat_interval',
            field=models.IntegerField(db_comment='自动重提醒间隔(分钟)', default=30, verbose_name='自动重提醒间隔(分钟)'),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='manual_alert_cooldown',
            field=models.IntegerField(db_comment='手动检测告警冷却(分钟)', default=5, verbose_name='手动检测告警冷却(分钟)'),
        ),
    ]
