# Generated by Django 4.2.7 on 2026-07-23 09:00

import apps.monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alertevent_last_notified_at_alertevent_notify_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortarget',
            name='alert_repeat_interval',
            field=models.IntegerField(db_comment='自动重提醒间隔(分钟)', default=apps.monitor.models._default_alert_repeat_interval, verbose_name='自动重提醒间隔(分钟)'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='manual_alert_cooldown',
            field=models.IntegerField(db_comment='手动检测告警冷却(分钟)', default=apps.monitor.models._default_manual_alert_cooldown, verbose_name='手动检测告警冷却(分钟)'),
        ),
    ]
