# Generated by Django 4.2.7 on 2026-07-21 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_rename_prj_module_idx_project_map_project_772106_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='所属分类')),
                ('access_method', models.CharField(choices=[('ssh', 'SSH'), ('local', '本地'), ('db', '数据库直连')], default='ssh', max_length=20, verbose_name='访问方式')),
                ('host', models.CharField(blank=True, default='', max_length=200, verbose_name='主机地址')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('username', models.CharField(blank=True, default='', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=200, verbose_name='密码')),
                ('ssh_key', models.TextField(blank=True, default='', verbose_name='SSH 私钥')),
                ('db_type', models.CharField(blank=True, choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlite', 'SQLite'), ('oracle', 'Oracle')], default='', max_length=20, verbose_name='数据库类型')),
                ('db_name', models.CharField(blank=True, default='', max_length=100, verbose_name='数据库名')),
                ('db_host', models.CharField(blank=True, default='', max_length=200, verbose_name='数据库主机')),
                ('db_port', models.IntegerField(blank=True, null=True, verbose_name='数据库端口')),
                ('db_username', models.CharField(blank=True, default='', max_length=100, verbose_name='数据库用户名')),
                ('db_password', models.CharField(blank=True, default='', max_length=200, verbose_name='数据库密码')),
                ('database_scope', models.CharField(blank=True, default='', max_length=200, verbose_name='数据库范围')),
                ('current_dir', models.CharField(blank=True, default='', max_length=500, verbose_name='默认目录')),
                ('status', models.CharField(choices=[('ready', '已就绪'), ('connecting', '连接中'), ('error', '连接失败'), ('disconnected', '未连接')], default='disconnected', max_length=20, verbose_name='状态')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='最近同步')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_environments', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '运维环境',
                'verbose_name_plural': '运维环境',
                'db_table': 'ops_environment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Text2SQLRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('query', '查询模式'), ('dml', '数据变更模式')], default='query', max_length=10, verbose_name='模式')),
                ('question', models.TextField(verbose_name='自然语言问题')),
                ('generated_sql', models.TextField(blank=True, default='', verbose_name='生成的 SQL')),
                ('validated_sql', models.TextField(blank=True, default='', verbose_name='校验后的 SQL')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('generated', '已生成 SQL'), ('validated', '已校验'), ('executed', '已执行'), ('failed', '失败')], default='draft', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text2sql_records', to='ops_tools.opsenvironment', verbose_name='环境')),
            ],
            options={
                'verbose_name': 'Text2SQL 记录',
                'verbose_name_plural': 'Text2SQL 记录',
                'db_table': 'text2sql_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogQuerySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_dir', models.CharField(blank=True, default='', max_length=500, verbose_name='日志目录')),
                ('current_file', models.CharField(blank=True, default='', max_length=500, verbose_name='当前文件')),
                ('content', models.TextField(blank=True, default='', verbose_name='日志内容')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='关键字')),
                ('tail_lines', models.IntegerField(default=200, verbose_name='最近行数')),
                ('is_realtime', models.BooleanField(default=False, verbose_name='实时查询')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sessions', to='ops_tools.opsenvironment', verbose_name='环境')),
            ],
            options={
                'verbose_name': '日志查询会话',
                'verbose_name_plural': '日志查询会话',
                'db_table': 'log_query_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileTransferTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('direction', models.CharField(choices=[('upload', '上传到服务器'), ('download', '下载到本地')], default='upload', max_length=10, verbose_name='方向')),
                ('remote_path', models.CharField(max_length=500, verbose_name='远程路径')),
                ('local_file', models.FileField(blank=True, null=True, upload_to='ops_transfer/%Y/%m/', verbose_name='本地文件')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='文件大小(bytes)')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '传输中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_transfers', to='ops_tools.opsenvironment', verbose_name='目标环境')),
            ],
            options={
                'verbose_name': '文件传输任务',
                'verbose_name_plural': '文件传输任务',
                'db_table': 'file_transfer_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
