# Generated by Django 4.2.7 on 2026-07-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasereview',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='评审评分(0-100)'),
        ),
    ]
