# Generated by Django 4.2.7 on 2026-07-18 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance_testing', '0002_performancescript_csv_datasets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('cron', models.CharField(max_length=200, verbose_name='Cron 表达式')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用')], default='enabled', max_length=16, verbose_name='状态')),
                ('thread_count', models.PositiveIntegerField(default=10, verbose_name='线程数')),
                ('ramp_up', models.PositiveIntegerField(default=5, verbose_name='Ramp-Up(秒)')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='持续时间(秒)')),
                ('realtime_enabled', models.BooleanField(default=False, verbose_name='启用实时报告')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='performance_testing.performancescript', verbose_name='关联脚本')),
            ],
            options={
                'verbose_name': '性能定时任务',
                'verbose_name_plural': '性能定时任务',
                'db_table': 'perf_scheduled_task',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='报告名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='performance_testing.performanceexecution', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': '性能测试报告',
                'verbose_name_plural': '性能测试报告',
                'db_table': 'perf_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
