# Generated by Django 4.2.7 on 2026-07-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0003_performancescheduledtask_performancereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeter_path', models.CharField(blank=True, default='', help_text='绝对路径，如 /opt/apache-jmeter-5.6.3/bin/jmeter；留空则使用环境变量或 PATH 中的 jmeter', max_length=500, verbose_name='JMeter 可执行路径')),
                ('realtime_report_enabled', models.BooleanField(default=False, verbose_name='启用实时报告')),
                ('influxdb_url', models.CharField(blank=True, default='', max_length=500, verbose_name='InfluxDB URL')),
                ('influxdb_org', models.CharField(blank=True, default='testhub', max_length=200, verbose_name='InfluxDB Org')),
                ('influxdb_bucket', models.CharField(blank=True, default='jmeter', max_length=200, verbose_name='InfluxDB Bucket')),
                ('influxdb_token', models.CharField(blank=True, default='', max_length=500, verbose_name='InfluxDB Token')),
                ('influxdb_measurement', models.CharField(blank=True, default='jmeter', max_length=200, verbose_name='InfluxDB Measurement')),
                ('influxdb_application', models.CharField(blank=True, default='testhub', max_length=200, verbose_name='InfluxDB Application')),
                ('max_threads', models.PositiveIntegerField(default=1000, verbose_name='最大线程数')),
                ('max_duration', models.PositiveIntegerField(default=7200, verbose_name='最大持续时间(秒)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '性能测试配置',
                'verbose_name_plural': '性能测试配置',
                'db_table': 'perf_config',
            },
        ),
    ]
