# Generated by Django 4.2.7 on 2026-07-18 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance_testing', '0007_performancescript_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancebatchexecution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.CreateModel(
            name='PerformanceScriptCsvFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='performance/csv/', verbose_name='CSV 文件')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to='performance_testing.performancescript', verbose_name='关联脚本')),
            ],
            options={
                'verbose_name': '性能脚本 CSV 文件',
                'verbose_name_plural': '性能脚本 CSV 文件',
                'db_table': 'perf_script_csv_file',
                'ordering': ['-created_at'],
            },
        ),
    ]
