# Generated by Django 4.2.7 on 2026-07-21 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0008_alter_performancebatchexecution_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceconfig',
            name='monitor_targets',
            field=models.JSONField(blank=True, default=list, help_text='执行性能测试时按时间窗采集这些目标的资源指标', verbose_name='监控目标列表'),
        ),
        migrations.AddField(
            model_name='performanceconfig',
            name='prometheus_enabled',
            field=models.BooleanField(default=False, verbose_name='启用 Prometheus 监控'),
        ),
        migrations.AddField(
            model_name='performanceconfig',
            name='prometheus_step',
            field=models.PositiveIntegerField(default=15, verbose_name='采集步长(秒)'),
        ),
        migrations.AddField(
            model_name='performanceconfig',
            name='prometheus_url',
            field=models.CharField(blank=True, default='', help_text='如 http://10.0.x.x:9090（Docker 内部可用 http://prometheus:9090）', max_length=500, verbose_name='Prometheus URL'),
        ),
        migrations.CreateModel(
            name='PerformanceMonitorMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=200, verbose_name='监控目标名称')),
                ('target_type', models.CharField(choices=[('app_server', '应用服务器'), ('db', '数据库'), ('redis', 'Redis/缓存'), ('gateway', '网关'), ('custom', '自定义微服务')], default='app_server', max_length=50, verbose_name='目标类型')),
                ('metric_key', models.CharField(max_length=100, verbose_name='指标键')),
                ('metric_label', models.CharField(max_length=100, verbose_name='指标中文名')),
                ('metric_unit', models.CharField(default='', max_length=20, verbose_name='单位')),
                ('timeline', models.JSONField(blank=True, default=list, verbose_name='时间线')),
                ('min_value', models.FloatField(default=0.0, verbose_name='最小')),
                ('avg_value', models.FloatField(default=0.0, verbose_name='平均')),
                ('max_value', models.FloatField(default=0.0, verbose_name='最大')),
                ('peak_value', models.FloatField(default=0.0, verbose_name='峰值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_metrics', to='performance_testing.performanceexecution', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': '监控指标',
                'verbose_name_plural': '监控指标',
                'db_table': 'perf_monitor_metric',
                'ordering': ['target_name', 'metric_key'],
                'indexes': [models.Index(fields=['execution'], name='perf_monito_executi_b0aebd_idx')],
            },
        ),
    ]
